[package]
name = "argtuner-interactive-probe"
version.workspace = true
edition.workspace = true

# This crate is not intended for publishing
publish = false

[dependencies]
argtuner-common = { workspace = true }
argtuner-talkback = { workspace = true, features = ["clap"] }
argtuner-talkback-derive = { workspace = true }
clap = { workspace = true, features = ["derive"] }
