[package]
name = "argtuner-loss-generator"
version.workspace = true
edition.workspace = true
license.workspace = true

# This crate is not intended for publishing
publish = false

[dependencies]
argtuner-talkback = { workspace = true, features = ["clap"] }
argtuner-talkback-derive.workspace = true
clap = { workspace = true, features = ["derive"] }
indicatif.workspace = true
rand.workspace = true
